### ISSUE TITLE
Record responses for all endpoints

### ISSUE THREAD

**Issue by gr2m** [octokit/fixtures#204]
We want to explore how to record responses for all endpoints of GitHub’s REST API.

Here is how I would approach this

1. Use `@octokit/routes` to generate a list of requests that would need to be sent. Use preview headers where they are required
3. Figure out required setups for each request. E.g. for "Add labels to issues" the setup would be
 	 1. Create repository
	 2. Create issue
	 3. Create label
	 Then after the "Add labels to issues" request was recorded, delete the temporary repository again.
	 We might be able to use the route path as an indication of the "hierarchy of requests", meaning what setup is needed to record a certain request.
4. Once we have the list requests together with necessary setups, we have to create user accounts and other resources need to send the requests, e.g. an organization and apps.
5. Run the requests, record the responses, referencing the routes recorded in `@ocotkit/routes` so the two can be combined easily.

The endpoint responses would differ from the current scenarios as they would all be a single request/response.

## Improvements

- Record response with all preview headers enabled for the endpoint.
- Normalize responses like we do in @octokit/fixtures
- Bonus: Once responses are normalized, we could add the responses to @octokit/fixtures for testing
- Reuse setups to record requests. E.g. when recording "create an issue", that setup can be used for "get an issue" and many others.

**Comment by gr2m** [comment]
For reference, in `octokit/fixtures` the setup is done all manual. For example, in the [project cards scenario](https://github.com/octokit/fixtures/blob/master/scenarios/api.github.com/project-cards/record.js) it creates

1. A temporary repository
2. A project in that repository
3. Two columns in that project

in order to be able to record a request to [move a project card](https://developer.github.com/v3/projects/cards/#move-a-project-card) (among others)

A declarative way would be much easier to maintain and collaborate on. It could look something like this

```yml
- name: move project card
- setup:
  - create project card
  - route: POST /projects/:project_id/columns
    previews: inertia
    project_id: {setup.project.id}
    name: column 2
- record:
  - route: POST /projects/columns/cards/{setup.card.id}/moves
    previews: inertia
    position: top
    column_id: {setup.column[1].id}
```

In the example above, the record requests options match the API of [octokit/request.js](https://github.com/octokit/request.js).

The setup could be names of other scenarios, `create project card` would create a repository, a project column and a card, after which we need to manually create a 2nd column so we can record the card move
